name: Tests

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    static-analysis:
        runs-on: ubuntu-24.04
        name: Static analysis
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: 8.3
            - name: Install dependencies
              run: composer install --no-interaction --no-progress --ansi
            - name: Psalm
              run: vendor/bin/psalm

    code-style:
        runs-on: ubuntu-24.04
        name: Code style
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: 8.3
            - name: Install dependencies
              run: composer install --no-interaction --no-progress --ansi
            - name: PHP-CS-Fixer
              run: vendor/bin/php-cs-fixer fix --dry-run

    tests:
        runs-on: ubuntu-24.04
        strategy:
            max-parallel: 1
            matrix:
                php:
                    - '8.3'
                include:
                    - description: 'lowest'
                      php: '8.3'
                      composer_option: '--prefer-lowest'
                    - description: '8.3'
                      php: '8.3'
        name: Tests PHP ${{ matrix.php }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Cache
              uses: actions/cache@v4
              with:
                  path: ~/.composer/cache/files
                  key: ${{ matrix.php }}-${{ matrix.composer_option }}
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
            - run: composer update --no-interaction --no-progress --ansi ${{ matrix.composer_option }}
            - run: vendor/bin/phpspec run
